### ISSUE TITLE
temperature not raised

### ISSUE THREAD

**Issue by phanesaleg** [nickjturner/homebridge-mi-temperature-and-humidity-sensor#2]
I installed 4 sensors, they are visible in homekit, but the temperature and humidity do not go up

**Comment by nickjturner** [comment]
Sorry for the slow response I've been away from my computer for a few weeks.

If they are shown in HomeKit but the temperature isn't changing that means the bluetooth connection has failed.

Can you share your config for the sensors so I can check everything looks good?
Also were the sensors all flashed to remove encryption?

If you set the logging to debug in homebridge you will see some additional logs like:
``` 
Started scanning
```
and
```
device found: a4:c1:38:b9:3f:72
```

if it is successfully found
