### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by ainshard** [nickjturner/homebridge-mi-temperature-and-humidity-sensor#3]
npm install --save homebridge-mi-temperature-and-humidity-sensor@1.0.4

[##################] \ reify:usb: timing reifyNode:node_modules/homebridge-mi-temperat
> @abandonware/bluetooth-hci-socket@0.5.3-8 install
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! install response status 404 Not Found on https://github.com/abandonware/node-bluetooth-hci-socket/releases/download/0.5.3-8/bluetooth_hci_socket-0.5.3-8-node-v93-linux-arm.tar.gz 
gyp ERR! build error / reify:usb: timing reifyNode:node_modules/homebridge-mi-temperat
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:10:17)
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:57:18
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at step (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:54:21)
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:71:22
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at subStep (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:69:33)
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:80:22
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! System Linux 3.10.108
gyp ERR! command "/volume1/@appstore/homebridge/app/bin/node" "/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/volume1/homebridge/node_modules/homebridge-mi-temperature-and-humidity-sensor/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node" "--module_name=bluetooth_hci_socket" "--module_path=/volume1/homebridge/node_modules/homebridge-mi-temperature-and-humidity-sensor/node_modules/@abandonware/bluetooth-hci-socket/lib/binding" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
gyp ERR! cwd /volume1/homebridge/node_modules/homebridge-mi-temperature-and-humidity-sensor/node_modules/@abandonware/bluetooth-hci-socket
gyp ERR! node -v v16.16.0
gyp ERR! node-gyp -v v9.0.0
gyp ERR! not ok 
node-pre-gyp ERR! build error sb: timing reifyNode:node_modules/homebridge-mi-temperat
node-pre-gyp ERR! stack Error: Failed to execute '/volume1/@appstore/homebridge/app/bin/node /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/volume1/homebridge/node_modules/homebridge-mi-temperature-and-humidity-sensor/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node --module_name=bluetooth_hci_socket --module_path=/volume1/homebridge/node_modules/homebridge-mi-temperature-and-humidity-sensor/node_modules/@abandonware/bluetooth-hci-socket/lib/binding --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/volume1/homebridge/node_modules/homebridge-mi-temperature-and-humidity-sensor/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
node-pre-gyp ERR! System Linux 3.10.108
node-pre-gyp ERR! command "/volume1/@appstore/homebridge/app/bin/node" "/volume1/homebridge/node_modules/homebridge-mi-temperature-and-humidity-sensor/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /volume1/homebridge/node_modules/homebridge-mi-temperature-and-humidity-sensor/node_modules/@abandonware/bluetooth-hci-socket
node-pre-gyp ERR! node -v v16.16.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.10
node-pre-gyp ERR! not ok 
Failed to execute '/volume1/@appstore/homebridge/app/bin/node /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/volume1/homebridge/node_modules/homebridge-mi-temperature-and-humidity-sensor/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node --module_name=bluetooth_hci_socket --module_path=/volume1/homebridge/node_modules/homebridge-mi-temperature-and-humidity-sensor/node_modules/@abandonware/bluetooth-hci-socket/lib/binding --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)

> @abandonware/noble@1.9.2-15 install
> node-gyp rebuild

gyp ERR! build error - reify:usb: timing reifyNode:node_modules/homebridge-mi-temperat
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:10:17)
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:57:18
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at step (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:54:21)
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:71:22
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at subStep (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:69:33)
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:80:22
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! System Linux 3.10.108
gyp ERR! command "/volume1/@appstore/homebridge/app/bin/node" "/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /volume1/homebridge/node_modules/homebridge-mi-temperature-and-humidity-sensor/node_modules/@abandonware/noble
gyp ERR! node -v v16.16.0
gyp ERR! node-gyp -v v9.0.0
gyp ERR! not ok 
npm ERR! code 1
npm ERR! path /volume1/homebridge/node_modules/homebridge-mi-temperature-and-humidity-sensor/node_modules/@abandonware/noble
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/packages/homebridge/home/.npm/_logs/2022-12-02T19_59_13_630Z-debug-0.log

Operation failed. Please review log for details.

**Comment by nickjturner** [comment]
Are you using homebridge UI to install or installing directly from terminal? 
What version of npm are you running?
Do you have other plugins running in homebridge?

**Comment by josin** [comment]
Same here. Using Homebridge on Rasberry with Ubuntu 20.04.5 in Docker.

> Are you using homebridge UI to install or installing directly from terminal?

Installed through HomeBridge UI.

> What version of npm are you running?
```shell
$ npm --version
8.19.2
```

> Do you have other plugins running in homebridge?
Yes, I do. For example `Homebridge Ewelink` works just fine.

**Comment by hartov** [comment]
Confirm. the same issue. I`m using synology DS220+
